### ISSUE TITLE
run example error

### ISSUE THREAD

**Issue by shiqinfeng1** [paritytrading/philadelphia#45] opened 2017-12-13 06:30 UTC
I want to test parity-system performance  with parity-sim, 
I do the following operations( using  default config ):
```
//startup parity-system
java -jar parity-system.jar ./etc/example.conf
//start parity simulator
java -jar parity-sim.jar ./etc/devel.conf
```
and parity-system  exit with following errors:
```
Exception in thread "main" java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:634)
	at java.base/java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:452)
	at com.paritytrading.parity.net.poe.POE$EnterOrder.get(POE.java:72)
	at com.paritytrading.parity.net.poe.POEServerParser.message(POEServerParser.java:37)
	at com.paritytrading.nassau.soupbintcp.SoupBinTCPServer.packet(SoupBinTCPServer.java:148)
	at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.parse(SoupBinTCPSession.java:125)
	at com.paritytrading.nassau.soupbintcp.SoupBinTCPSession.receive(SoupBinTCPSession.java:93)
	at com.paritytrading.parity.system.Events.receive(Events.java:95)
	at com.paritytrading.parity.system.Events.run(Events.java:68)
	at com.paritytrading.parity.system.TradingSystem.main(TradingSystem.java:47)
	at com.paritytrading.parity.system.TradingSystem.main(TradingSystem.java:27)
```
the code is : 
https://github.com/paritytrading/parity/blob/master/libraries/net/src/main/java/com/paritytrading/parity/net/poe/POE.java#L72

but I dont know why it happens.

**Comment by jvirtanen** [comment] 2017-12-13 09:28
Hi @shiqinfeng1! This is a duplicate of [#9](https://github.com/paritytrading/parity-extras/issues/9) on [Parity Extras](https://github.com/paritytrading/parity-extras). Let's track the progress over there.

**Closed by jvirtanen** 2017-12-13 09:28 UTC
